addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.9.2")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.mintbeans"    % "sbt-ecr"             % "0.16.0")
